# Generated by Django 2.2 on 2019-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.TextField(null=True),
        ),
    ]
