# Generated by Django 2.2 on 2019-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20190504_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='shop_user',
        ),
    ]
