# Generated by Django 2.2 on 2019-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_auto_20190504_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingre_name', models.TextField(max_length=50)),
                ('is_empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.TextField(max_length=100)),
                ('is_daily_menu', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=200, null=True)),
                ('normal_price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('menu_type', models.CharField(choices=[('01', 'อาหาร'), ('02', 'เครื่องดื่ม')], default='01', max_length=2)),
                ('menu_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
