# Generated by Django 2.2 on 2019-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_auto_20190504_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.FileField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
