# Generated by Django 2.2 on 2019-05-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20190504_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_user',
            new_name='shop_host',
        ),
    ]
