# Generated by Django 2.2 on 2019-05-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_auto_20190504_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_shop',
            new_name='ingredient_of',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_shop',
            new_name='menu_of',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
