# Generated by Django 2.2 on 2019-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_shop_shop_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='close_time',
            field=models.CharField(choices=[('01', 'ก่อน 8:00'), ('02', '8:00 - 9:00'), ('03', '9:00 - 10:00'), ('04', '10:00 - 11:00'), ('05', '11:00 - 12:00'), ('06', '12:00 - 13:00'), ('07', '13:00 - 14:00'), ('08', '14:00 - 15:00'), ('09', '15:00 - 16:00'), ('10', '16:00 - 17:00'), ('11', '17:00 - 18:00'), ('12', 'หลัง 18:00')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_time',
            field=models.CharField(choices=[('01', 'ก่อน 8:00'), ('02', '8:00 - 9:00'), ('03', '9:00 - 10:00'), ('04', '10:00 - 11:00'), ('05', '11:00 - 12:00'), ('06', '12:00 - 13:00'), ('07', '13:00 - 14:00'), ('08', '14:00 - 15:00'), ('09', '15:00 - 16:00'), ('10', '16:00 - 17:00'), ('11', '17:00 - 18:00'), ('12', 'หลัง 18:00')], max_length=2, null=True),
        ),
    ]
