# Generated by Django 2.2 on 2019-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_auto_20190505_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
