# Generated by Django 2.2 on 2019-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_history'),
        ('ordering', '0014_auto_20190505_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_of',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.CASCADE, to='accounts.History'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_of',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.PROTECT, to='ordering.Shop'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_of',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.PROTECT, to='ordering.Shop'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
