# Generated by Django 2.2 on 2019-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_auto_20190505_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
