# Generated by Django 2.2 on 2019-05-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0017_auto_20190505_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='special_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
