# Generated by Django 2.2 on 2019-05-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0018_auto_20190506_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_of',
            new_name='save_to',
        ),
    ]
