# Generated by Django 2.2 on 2019-05-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20190506_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='this_queue',
            field=models.IntegerField(default=999999999),
        ),
        migrations.CreateModel(
            name='ShopQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.IntegerField(default=0)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ordering.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='queue',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.PROTECT, to='ordering.ShopQueue'),
        ),
    ]
