# Generated by Django 2.2 on 2019-05-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0020_auto_20190506_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='save_to',
        ),
        migrations.RemoveField(
            model_name='order',
            name='this_queue',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='queue',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.PROTECT, to='ordering.ShopQueue'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='this_queue',
            field=models.IntegerField(default=999999999),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wait',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AddField(
            model_name='shopqueue',
            name='current_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopqueue',
            name='last_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
