# Generated by Django 2.2 on 2019-05-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0021_auto_20190506_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userprofile',
        ),
    ]
