# Generated by Django 2.2 on 2019-05-08 01:04

from django.db import migrations, models
import ordering.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0023_auto_20190506_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.FileField(blank=True, null=True),
        ),
    ]
