# Generated by Django 2.2 on 2019-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0024_auto_20190508_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=100),
        ),
    ]
