# Generated by Django 2.2 on 2019-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0025_auto_20190513_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(default='some ingredient', max_length=50),
        ),
    ]
