# Generated by Django 2.2 on 2019-05-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0027_auto_20190513_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='phone_number',
        ),
    ]
