# Generated by Django 2.2 on 2019-05-01 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('01', 'customer'), ('02', 'shop')], default='01', max_length=2)),
                ('phone_number', models.IntegerField(max_length='10')),
            ],
        ),
    ]
