# Generated by Django 2.2 on 2019-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(max_length='10', null=True),
        ),
    ]
