# Generated by Django 2.2 on 2019-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190502_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
