# Generated by Django 2.2 on 2019-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_first_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_last_name',
            field=models.TextField(null=True),
        ),
    ]
