# Generated by Django 2.2 on 2019-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
