# Generated by Django 2.2 on 2019-05-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_history_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='userprofile',
        ),
    ]
