# Generated by Django 2.2 on 2019-05-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190506_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='userprofile',
            new_name='user',
        ),
    ]
