# Generated by Django 2.2 on 2019-05-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190507_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='history',
            name='order_datetime',
        ),
        migrations.RemoveField(
            model_name='history',
            name='shop',
        ),
        migrations.CreateModel(
            name='PersonalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(default='some menu')),
                ('shop', models.TextField(default='some shop')),
                ('order_datetime', models.DateTimeField(null=True)),
                ('price', models.FloatField(default=0)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.History')),
            ],
        ),
    ]
